#!/bin/bash
/usr/bin/systemctl restart monit

# Increase the memory limit for PHP scripts to 512M (default is 128M)
# This is required for heavier scripts such as NEMS Tactical Overview
for file in `find /etc/php/*/apache2/ -name 'php.ini' -exec grep -l "memory_limit = 128M" {} +`; do
  echo "Increasing PHP script memory limit from 128M to 512M [$file]"
  sed -ir 's/memory_limit\s*=.*/memory_limit = 512M/g' $file
done
