[WebService]
UrlRoot = /cockpit/
ProtocolHeader = X-Forwarded-Proto
ForwardedForHeader = X-Forwarded-For
LoginTitle = NEMS Linux System Management
Origins = https://* http://* wss://* ws://*
AllowUnencrypted = true
